services:

  # ------ MS MAQUINA ------
  db-maquina:
    image: postgres:16-alpine
    container_name: db-maquina
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_maquina
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data/maquina:/var/lib/postgresql/data
    networks:
      - sus_network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-maquina:
    build:
      context: .
      dockerfile: ./ms-maquina/Dockerfile
    container_name: ms-maquina
    ports:
      - "8081:8081"
      - "5006:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-maquina:5432/db_maquina
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD:  postgres
      APP_JWT_SECRET: minhaChaveUltraSecretaComMaisDe32Bytes
      APP_JWT_EXPIRATION_MS: 3600000
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MAQUINA_SERVICE_URL: http://ms-maquina:8081/maquinas
      INTERNAL_SECRET: my-secret-key
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      db-maquina:
        condition: service_healthy
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_started
    restart: on-failure
    networks:
      - sus_network

  # ------  MS OPERACAO ------
  db-operacao:
    image: postgres:16-alpine
    container_name: db-operacao
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_operacao
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres_data/operacao:/var/lib/postgresql/data
    networks:
      - sus_network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-operacao:
    build:
      context: .
      dockerfile: ./ms-operacao/Dockerfile
    container_name: ms-operacao
    ports:
      - "8082:8082"
      - "5007:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-operacao:5432/db_operacao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: minhaChaveUltraSecretaComMaisDe32Bytes
      APP_JWT_EXPIRATION_MS: 3600000
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OPERACAO_SERVICE_URL: http://ms-operacao:8082/operacoes
      INTERNAL_SECRET: my-secret-key
      OPERACAO_SERVICE_HOST: ms-operacao
      OPERACAO_SERVICE_PORT: 8082
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"
    depends_on:
      db-operacao:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ms-maquina:
        condition: service_started
    restart: on-failure
    networks:
      - sus_network

  # ------  MS OPERACAO-MAQUINA ------
  db-operacao-maquina:
    image: postgres:16-alpine
    container_name: db-operacao-maquina
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_operacao_maquina
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres_data/operacao_maquina:/var/lib/postgresql/data
    networks:
      - sus_network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-operacao-maquina:
    build:
      context: .
      dockerfile: ./ms-operacao-maquina/Dockerfile
    container_name: ms-operacao-maquina
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-operacao-maquina:5432/db_operacao_maquina
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: minhaChaveUltraSecretaComMaisDe32Bytes
      APP_JWT_EXPIRATION_MS: 3600000
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OPERACAO_MAQUINA_SERVICE_URL: http://ms-operacao-maquina:8080/operacoes_maquinas
      INTERNAL_SECRET: my-secret-key
      OPERACAO_MAQUINA_SERVICE_HOST: ms-operacao-maquina
      OPERACAO_MAQUINA_SERVICE_PORT: 8080
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      db-operacao-maquina:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ms-maquina:
        condition: service_started
    restart: on-failure
    networks:
      - sus_network

    # ------ KAFKA E ZOOKEEPER ------
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_CLIENT_PORT: 2181
      ZOO_TICK_TIME: 2000
    networks:
      - sus_network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sus_network
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:9092 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 15s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: meu-hospital-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - sus_network



networks:
  sus_network:
    driver: bridge










##-------------------------------------------------------------------
  # ------  MS NOTIFICACAO ------
#  ms-notificacao:
#    build:
#      context: .
#      dockerfile: ./ms-notificacao/Dockerfile
#    container_name: ms-notificacao
#    ports:
#      - "8082:8082"
#    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DB}?authSource=admin
#      SPRING_MAIL_HOST: mailhog
#      SPRING_MAIL_PORT: 1025
#    depends_on:
#      kafka:
#        condition: service_healthy
#      mailhog:
#        condition: service_started
#      db-notificacao-mongo:
#        condition: service_started
#    restart: on-failure
#    networks:
#      - hospital_network
#
#  db-notificacao-mongo:
#    image: mongo:6.0
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
#      MONGO_INITDB_DATABASE: ${MONGODB_DB}
#    volumes:
#      - ./data/mongo_data/notificacao:/data/db
#    networks:
#      - hospital_network
#    restart: always
#
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    ports:
#      - "8083:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
#      ME_CONFIG_BASICAUTH_USERNAME: user_express
#      ME_CONFIG_BASICAUTH_PASSWORD: password_express
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
#      ME_CONFIG_MONGODB_DATABASE: ${MONGODB_DB}
#    depends_on:
#      - db-notificacao-mongo
#    networks:
#      - hospital_network
#
#  # ------ MS HISTORICO ------
#  db-historico:
#    image: postgres:16-alpine
#    container_name: db-historico
#    volumes:
#      - ./data/postgres_data/historico:/var/lib/postgresql/data
#    networks:
#      - hospital_network
#    ports:
#      - "5434:5432"
#    restart: always
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    environment:
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${HISTORICO_DB_NAME}
#
#  ms-historico:
#    build:
#      context: .
#      dockerfile: ms-historico/Dockerfile
#    container_name: ms-historico
#    ports:
#      - "8084:8084"
#    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db-historico:5432/${HISTORICO_DB_NAME}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#      APP_JWT_SECRET: ${JWT_SECRET}
#      APP_JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
#    depends_on:
#      db-historico:
#        condition: service_healthy
#      kafka:
#        condition: service_healthy
#    networks:
#      - sus_network
#    restart: always
#
#  # ------ KAFKA E ZOOKEEPER ------
#  zookeeper:
#    image: zookeeper:3.8
#    container_name: zookeeper
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_CLIENT_PORT: 2181
#      ZOO_TICK_TIME: 2000
#    networks:
#      - sus_network
#
#  kafka:
#    image: confluentinc/cp-kafka:7.6.0
#    container_name: kafka
#    depends_on:
#      zookeeper:
#        condition: service_started
#    ports:
#      - "9092:9092"
#      - "9093:9093"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - hospital_network
#    healthcheck:
#      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:9092 || exit 1" ]
#      interval: 10s
#      timeout: 10s
#      retries: 20
#      start_period: 15s
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "8085:8080"
#    depends_on:
#      - kafka
#    environment:
#      KAFKA_CLUSTERS_0_NAME: meu-hospital-cluster
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#    networks:
#      - sus_network
#
#  # ------ MAILHOG SMTP ------
#  mailhog:
#    image: mailhog/mailhog
#    container_name: mailhog
#    platform: linux/amd64
#    ports:
#      - "1025:1025"
#      - "8025:8025"
#    networks:
#      - sus_network

