server:
  port: 8080

spring:
  application:
    name: ms-maquina
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_maquina
    #url: jdbc:postgresql://db-maquina:5432/db_maquina
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


jwt:
  secret: ${JWT_SECRET_KEY:minhaChaveUltraSecretaComMaisDe32Bytes}
  prazoExpiracao: ${JWT_EXPIRATION_TIME:3600000}

auth:
  service:
    url: http://auth-service:8081


meumenu:
  admin:
    login: ${DEFAULT_ADMIN_LOGIN:admin}
    email: ${DEFAULT_ADMIN_EMAIL:admin@meumenu.com}
    password: ${DEFAULT_ADMIN_PASSWORD:SenhaForte123!}
